basePath: /
definitions:
  model.StatisticsMeta:
    properties:
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    url: http://www.swagger.io/support
  description: 统计 api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 文档
  version: "0.1"
paths:
  /v1/statistics/interval:
    get:
      consumes:
      - application/json
      parameters:
      - description: 标题
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.StatisticsMeta'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 获取某时间段内的统计数据和
      tags:
      - GetIntervalData
  /v1/statistics/interval/unit:
    get:
      consumes:
      - application/json
      parameters:
      - description: 标题
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.StatisticsMeta'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 获取某时间段内根据某时间单位分组的统计数据
      tags:
      - GetIntervalUnitData
  /v1/statistics/meta:
    get:
      consumes:
      - application/json
      parameters:
      - description: 标题
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.StatisticsMeta'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 获取 meta 列表
      tags:
      - GetMetas
    post:
      consumes:
      - application/json
      parameters:
      - description: 标题
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.StatisticsMeta'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"创建成功"}'
          schema:
            type: string
      summary: 创建 meta
      tags:
      - CreateMetas
swagger: "2.0"
